version: '3.8'
services:
  app:
    image: node:latest
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000" # Replace with the actual port used by the application
    command: >
      sh -c "yarn install
      && yarn start"
    environment:
      - NODE_ENV=development # or production, depending on the use case
      - ATLAS_URI=mongodb://mongo:27017/Lite # URI for connecting to the MongoDB service
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=Lite # Initial database name

# Networks to enable communication between containers
networks:
  default:
    driver: bridge
